version: '3.8'

volumes:
  postgres_data:
  static_value:
  media_value:

networks:
  foodgram-network:

services:
    db:
      container_name: foodgram_db
      image: postgres:13.0-alpine
      restart: unless-stopped
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ../.env
      networks:
        - foodgram-network

    backend:
      container_name: foodgram_backend
      # image: octrow/foodgram_backend:latest
      build:
        context: ../backend
        dockerfile: Dockerfile
      # command: cp -r /app/collected_static/. /app/static/
      restart: unless-stopped
      volumes:
        - static_value:/app/static/
        - media_value:/app/media/
      depends_on:
        - db
      env_file:
        - ../.env
      networks:
        - foodgram-network

    frontend:
      container_name: foodgram_frontend
      image: octrow/foodgram_frontend:latest
      # build:
      #   context: ../frontend
      #   dockerfile: Dockerfile
      depends_on:
        - db
        - backend
      volumes:
        - ../frontend/:/app/result_build/
      networks:
        - foodgram-network

    nginx:
      container_name: foodgram_nginx
      image: nginx:1.21.3-alpine
      restart: unless-stopped
      ports:
        - "80:80"
      volumes:
        - ./nginx-local.conf:/etc/nginx/conf.d/default.conf
        - ../frontend/build:/usr/share/nginx/html/
        - ../docs/:/usr/share/nginx/html/api/docs/
        - static_value:/var/html/static/
        - media_value:/var/html/media/
      depends_on:
        - backend
        - frontend
      networks:
        - foodgram-network

