# Generated by Django 4.2.5 on 2023-10-08 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_amountingredient_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amountingredient',
            unique_together=set(),
        ),
    ]
