# Generated by Django 4.2.5 on 2023-10-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_subscription_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='\nusers_customuser username and email must be unique\n',
        ),
    ]
