# Generated by Django 4.2.5 on 2023-10-09 22:52

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_ingredient_unique_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Введите количество ингредиента в единицах измерения', validators=[django.core.validators.MinValueValidator(1, message='Должно быть больше нуля'), django.core.validators.MaxValueValidator(32767, message='Число должно быть меньше чем {settings.MAX_VALUE}')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Введите HEX-код цвета тега', image_field=None, max_length=25, samples=None, unique=True, verbose_name='HEX-код'),
        ),
    ]
