# Generated by Django 4.2.5 on 2023-10-09 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Введите количество ингредиента в единицах измерения', validators=[django.core.validators.MinValueValidator(1, message='Должно быть 1 и больше'), django.core.validators.MaxValueValidator(32767, message='Число должно быть меньше чем {settings.MAX_VALUE}')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Введите время приготовления рецепта в минутах', validators=[django.core.validators.MinValueValidator(1, message='Минимум 1 минута!'), django.core.validators.MaxValueValidator(32767, message='Максимум 32767 минут!')], verbose_name='Время приготовления'),
        ),
    ]
