# Generated by Django 4.2.5 on 2023-10-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Введите уникальное имя пользователя', max_length=150, unique=True, verbose_name='Никнейм'),
        ),
    ]
