# Generated by Django 4.2.5 on 2023-10-09 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Введите уникальное имя пользователя', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Юзернейм может содержать только цифры, латинские буквы, знаки (не в начале): тире, точка и нижнее тире.', regex='^[a-zA-Z0-9]+([_.-]?[a-zA-Z0-9])*$')], verbose_name='Никнейм'),
        ),
    ]
